DROP TABLE IF EXISTS TAREAS;
 DROP TABLE IF EXISTS usuario;
  DROP TABLE IF EXISTS Phones;
CREATE TABLE TAREAS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  descripcion VARCHAR(250) NOT NULL
);
CREATE TABLE usuario(
id INT  AUTO_INCREMENT  PRIMARY KEY,
 name VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
  password VARCHAR(20) NOT NULL,
  FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  
);

CREATE TABLE Phones(
id INT  PRIMARY KEY,
  numero  INTEGER NOT NULL,
  citycode INTEGER NOT NULL,
  contrycode INTEGER NOT NULL
);

 ALTER TABLE Phones
    ADD FOREIGN KEY (ID) 
    REFERENCES usuario(ID)