DROP TABLE IF EXISTS TAREAS;
 
CREATE TABLE TAREAS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  descripcion VARCHAR(250) NOT NULL,
  fcreated VARCHAR(30) NOT NULL,
  isactive bool NOT NULL
);